"""fix_missing_fks

Revision ID: 99572e6427a6
Revises: 102ce44de1b1
Create Date: 2026-01-20 08:27:25.149240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99572e6427a6'
down_revision: Union[str, Sequence[str], None] = '102ce44de1b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_foreign_key(None, 'packages', 'delivery_locations', ['delivery_location_id'], ['id'])
    # op.create_foreign_key(None, 'tracking_events', 'locations', ['location_id'], ['location_string'])
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_packages_delivery_location', 'delivery_locations', ['delivery_location_id'], ['id'])
    with op.batch_alter_table('tracking_events', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_tracking_events_locations', 'locations', ['location_id'], ['location_string'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tracking_events', type_='foreignkey')
    op.drop_constraint(None, 'packages', type_='foreignkey')
    # ### end Alembic commands ###
